name: Run Yahoo Finance Script

on:
  schedule:
    - cron: "0 4 * * 1-5" # 9:30 AM IST = 4:00 AM UTC, Mon–Fri
  workflow_dispatch: # Manual trigger option

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python filter-stocks-script-gautam.py
